# Generated by Django 6.0.7 on 2026-08-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0007_alter_product_options"),
        ("shopapp", "0007_alter_product_options_alter_product_discount"),
    ]

    operations = []
